# Image Preprocessing
resize_dim: [128, 128] # Target H, W for U-Net input
normalization_mean: [0.485, 0.456, 0.406] # ImageNet mean
normalization_std: [0.229, 0.224, 0.225]   # ImageNet std

# Data Augmentation (applied during training)
augmentation:
  random_crop_prob: 0.5
  random_rotation_degrees: 15
  random_horizontal_flip_prob: 0.5
  # Add more if needed

# Graph Feature Processing
sobel_kernel_size: 3
gaussian_blur_kernel_size: [5, 5]
gaussian_blur_sigma: 1.0